### ISSUE TITLE
Update project repository description

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Sprint-2019-Detroit/Sandbox-Data-Tool#1]
Based on the work done in Detroit please consider updating the Project repo description.

![SandboxDataTool](https://user-images.githubusercontent.com/25934611/61313745-b8f2f380-a7c0-11e9-8571-fd951fac9b1a.jpg)

**Comment by vtangToD** [comment]
Hi @jacebryan, I don't have access to the settings for this repo. I assumed I would have admin access to this repo since I started it, or do I need to get you to set that up for me separately? I'd also like to change the project name.

**Comment by jacebryan** [comment]
Hi @vtangToD!

The reason you don't have access to Settings is because of the base permissions we've set on the Organization. Everyone who is a Member has Write access but not Admin access.

Besides updating the name of the project what else do you need done? I can help :)

P.S. What is the new name for the repo?

**Comment by vtangToD** [comment]
Hi @jacebryan , 
We just need to update the project/repo name to "Sandbox Sample Data Set" / Sandbox-Sample-Data-Set and the Project Description to:
This project is a set of sample data that can be used to populate a clean NPSP install (e.g. a scratch org). It’s intended to be used for learning purposes, e.g. training new users or new admins of NPSP to get them familiar with the base platform.
Thanks!

**Comment by jacebryan** [comment]
@vtangToD - Done! Closing this Issue now.
